INSERT INTO `states` (`name`, `country_id`) VALUES
('Andhra Pradesh', 94),
('Arunachal Pradesh', 94),
('Assam', 94),
('Bihar', 94),
('Chattisgarh', 94),
('Goa', 94),
('Gujrat', 94),
('Haryana', 94),
('Himachal Pradesh', 94),
('Jharkhand', 94),
('Karnataka', 94),
('Kerala', 94),
('Madhya Pradesh', 94),
('Maharashtra', 94),
('Manipur', 94),
('Meghalaya', 94),
('Mizoram', 94),
('Nagaland', 94),
('Orissa', 94),
('Punjab', 94),
('Rajasthan', 94),
('Sikkim', 94),
('Tamil Nadu', 94),
('Telangana', 94),
('Tripura', 94),
('Uttarakhand', 94),
('Uttar Pradesh', 94),
('West Bengal', 94),
('Andaman & Nicobar', 94),
('Chandigarh', 94),
('Daman & Diu', 94),
('Delhi', 94),
('Jammu & Kashmir', 94),
('Ladakh', 94),
('Lakshadweep', 94),
('Puducherry', 94);



